import React, { createContext, useState, useEffect } from "react";

// Create the Recipe Context
export const RecipeContext = createContext();

// Sample data for initial recipes
const sampleRecipes = [
  {
    id: "1",
    name: "Chili Colorado",
    description: "Mexikanisches Chili mit roter Sauce und Rindfleisch",
    image: "",
    ingredients: [
      { name: "Rindfleisch", amount: "800", unit: "g", category: "Fleisch" },
      { name: "Chilischoten", amount: "6", unit: "Stück", category: "Gemüse" },
      { name: "Tomaten", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Zwiebeln", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Knoblauch", amount: "4", unit: "Zehen", category: "Gemüse" },
      { name: "Kreuzkümmel", amount: "1", unit: "TL", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 120,
    servings: 4,
    calories: 450,
    categories: ["Hauptgericht", "Mexikanisch", "Scharf"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Scharf",
  },
  {
    id: "2",
    name: "Burger",
    description: "Klassischer Burger mit Hackfleisch-Patty",
    image: "",
    ingredients: [
      { name: "Hackfleisch", amount: "600", unit: "g", category: "Fleisch" },
      { name: "Burgerbrötchen", amount: "4", unit: "Stück", category: "Brot" },
      {
        name: "Käse",
        amount: "4",
        unit: "Scheiben",
        category: "Milchprodukte",
      },
      { name: "Tomaten", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Salat", amount: "100", unit: "g", category: "Gemüse" },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    calories: 650,
    categories: ["Hauptgericht", "Fast Food", "Amerikanisch"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "3",
    name: "Pizza",
    description: "Hausgemachte Pizza mit Tomatensauce und Belag",
    image: "",
    ingredients: [
      { name: "Pizzateig", amount: "500", unit: "g", category: "Teigwaren" },
      { name: "Tomatensauce", amount: "200", unit: "ml", category: "Saucen" },
      {
        name: "Mozzarella",
        amount: "250",
        unit: "g",
        category: "Milchprodukte",
      },
      { name: "Salami", amount: "100", unit: "g", category: "Fleisch" },
      { name: "Champignons", amount: "150", unit: "g", category: "Gemüse" },
      { name: "Oregano", amount: "1", unit: "TL", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    calories: 580,
    categories: ["Hauptgericht", "Italienisch", "Vegetarisch"],
    difficulty: "Mittel",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "4",
    name: "Flammenkuchen",
    description: "Elsässischer Flammkuchen mit Speck und Zwiebeln",
    image: "",
    ingredients: [
      {
        name: "Flammkuchenteig",
        amount: "400",
        unit: "g",
        category: "Teigwaren",
      },
      { name: "Schmand", amount: "200", unit: "g", category: "Milchprodukte" },
      { name: "Speck", amount: "150", unit: "g", category: "Fleisch" },
      { name: "Zwiebeln", amount: "2", unit: "Stück", category: "Gemüse" },
      {
        name: "Crème fraîche",
        amount: "100",
        unit: "g",
        category: "Milchprodukte",
      },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Französisch", "Herzhaft"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "5",
    name: "Fitnesswaffeln",
    description: "Gesunde Waffeln mit wenig Zucker und hohem Proteingehalt",
    image: "",
    ingredients: [
      { name: "Haferflocken", amount: "200", unit: "g", category: "Getreide" },
      { name: "Eier", amount: "3", unit: "Stück", category: "Eier" },
      {
        name: "Magerquark",
        amount: "250",
        unit: "g",
        category: "Milchprodukte",
      },
      { name: "Banane", amount: "1", unit: "Stück", category: "Früchte" },
      { name: "Backpulver", amount: "1", unit: "TL", category: "Backzutaten" },
    ],
    instructions: [],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    calories: 280,
    categories: ["Frühstück", "Fitness", "Gesund"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Süß",
  },
  {
    id: "6",
    name: "Pancakes",
    description: "Fluffige amerikanische Pfannkuchen",
    image: "",
    ingredients: [
      { name: "Mehl", amount: "250", unit: "g", category: "Getreide" },
      { name: "Milch", amount: "300", unit: "ml", category: "Milchprodukte" },
      { name: "Eier", amount: "2", unit: "Stück", category: "Eier" },
      { name: "Zucker", amount: "50", unit: "g", category: "Backzutaten" },
      { name: "Backpulver", amount: "2", unit: "TL", category: "Backzutaten" },
      { name: "Butter", amount: "30", unit: "g", category: "Milchprodukte" },
    ],
    instructions: [],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 320,
    categories: ["Frühstück", "Amerikanisch", "Süß"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Süß",
  },
  {
    id: "7",
    name: "Bolognese",
    description: "Klassische italienische Fleischsauce",
    image: "",
    ingredients: [
      { name: "Hackfleisch", amount: "500", unit: "g", category: "Fleisch" },
      {
        name: "Tomaten passiert",
        amount: "800",
        unit: "g",
        category: "Gemüse",
      },
      { name: "Zwiebeln", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Karotten", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Sellerie", amount: "1", unit: "Stange", category: "Gemüse" },
      { name: "Rotwein", amount: "100", unit: "ml", category: "Getränke" },
      { name: "Nudeln", amount: "400", unit: "g", category: "Teigwaren" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Italienisch", "Pasta"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "8",
    name: "Bolognese 4h",
    description: "Langsam geschmorte Bolognese für intensiven Geschmack",
    image: "",
    ingredients: [
      { name: "Hackfleisch", amount: "600", unit: "g", category: "Fleisch" },
      {
        name: "Tomaten passiert",
        amount: "1000",
        unit: "g",
        category: "Gemüse",
      },
      { name: "Zwiebeln", amount: "3", unit: "Stück", category: "Gemüse" },
      { name: "Karotten", amount: "3", unit: "Stück", category: "Gemüse" },
      { name: "Sellerie", amount: "2", unit: "Stangen", category: "Gemüse" },
      { name: "Rotwein", amount: "200", unit: "ml", category: "Getränke" },
      { name: "Milch", amount: "100", unit: "ml", category: "Milchprodukte" },
      { name: "Nudeln", amount: "400", unit: "g", category: "Teigwaren" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 240,
    servings: 6,
    calories: 550,
    categories: ["Hauptgericht", "Italienisch", "Geschmort"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "9",
    name: "Lasagne",
    description:
      "Klassische italienische Lasagne mit Bolognese und Béchamelsauce",
    image: "",
    ingredients: [
      {
        name: "Lasagneplatten",
        amount: "300",
        unit: "g",
        category: "Teigwaren",
      },
      { name: "Hackfleisch", amount: "500", unit: "g", category: "Fleisch" },
      {
        name: "Tomaten passiert",
        amount: "800",
        unit: "g",
        category: "Gemüse",
      },
      { name: "Béchamelsauce", amount: "500", unit: "ml", category: "Saucen" },
      { name: "Parmesan", amount: "100", unit: "g", category: "Milchprodukte" },
      {
        name: "Mozzarella",
        amount: "200",
        unit: "g",
        category: "Milchprodukte",
      },
    ],
    instructions: [],
    prepTime: 30,
    cookTime: 45,
    servings: 6,
    calories: 620,
    categories: ["Hauptgericht", "Italienisch", "Auflauf"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Cremig",
  },
  {
    id: "10",
    name: "Baked Creamy Fish",
    description: "Überbackener Fisch in cremiger Sauce",
    image: "",
    ingredients: [
      { name: "Fischfilet", amount: "600", unit: "g", category: "Fisch" },
      { name: "Sahne", amount: "200", unit: "ml", category: "Milchprodukte" },
      { name: "Käse", amount: "150", unit: "g", category: "Milchprodukte" },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Knoblauch", amount: "2", unit: "Zehen", category: "Gemüse" },
      { name: "Dill", amount: "1", unit: "Bund", category: "Kräuter" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Fisch", "Cremig"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Cremig",
  },
  {
    id: "11",
    name: "Chili con Carne",
    description: "Mexikanisches Chili mit Hackfleisch und Bohnen",
    image: "",
    ingredients: [
      { name: "Hackfleisch", amount: "600", unit: "g", category: "Fleisch" },
      {
        name: "Kidneybohnen",
        amount: "400",
        unit: "g",
        category: "Hülsenfrüchte",
      },
      { name: "Tomaten", amount: "800", unit: "g", category: "Gemüse" },
      { name: "Paprika", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Zwiebeln", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Chilipulver", amount: "2", unit: "TL", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 60,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Mexikanisch", "Scharf"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Scharf",
  },
  {
    id: "12",
    name: "Rotbreisauce (Rotkohl Kartoffelbrei braune Sauce) Hähnchenbrustfilet",
    description: "Hähnchenbrust mit Rotkohl, Kartoffelbrei und brauner Sauce",
    image: "",
    ingredients: [
      {
        name: "Hähnchenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Rotkohl", amount: "500", unit: "g", category: "Gemüse" },
      { name: "Kartoffeln", amount: "800", unit: "g", category: "Gemüse" },
      { name: "Milch", amount: "100", unit: "ml", category: "Milchprodukte" },
      { name: "Butter", amount: "50", unit: "g", category: "Milchprodukte" },
      { name: "Bratensauce", amount: "200", unit: "ml", category: "Saucen" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Deutsch", "Traditionell"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "13",
    name: "Rotbreisauce (Rotkohl Kartoffelbrei braune Sauce) Schweinelende",
    description: "Schweinelende mit Rotkohl, Kartoffelbrei und brauner Sauce",
    image: "",
    ingredients: [
      { name: "Schweinelende", amount: "600", unit: "g", category: "Fleisch" },
      { name: "Rotkohl", amount: "500", unit: "g", category: "Gemüse" },
      { name: "Kartoffeln", amount: "800", unit: "g", category: "Gemüse" },
      { name: "Milch", amount: "100", unit: "ml", category: "Milchprodukte" },
      { name: "Butter", amount: "50", unit: "g", category: "Milchprodukte" },
      { name: "Bratensauce", amount: "200", unit: "ml", category: "Saucen" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 45,
    servings: 4,
    calories: 540,
    categories: ["Hauptgericht", "Deutsch", "Traditionell"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "14",
    name: "Hähnchenbrustfilet Krokkoli Kroketten Brokkoli",
    description: "Hähnchenbrust mit Kroketten und Brokkoli",
    image: "",
    ingredients: [
      {
        name: "Hähnchenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Kroketten", amount: "500", unit: "g", category: "Beilage" },
      { name: "Brokkoli", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Butter", amount: "30", unit: "g", category: "Milchprodukte" },
      { name: "Salz", amount: "1", unit: "TL", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Einfach", "Klassisch"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "15",
    name: "Putenbrustfilet Krokkoli",
    description: "Putenbrust mit Brokkoli",
    image: "",
    ingredients: [
      {
        name: "Putenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Brokkoli", amount: "500", unit: "g", category: "Gemüse" },
      { name: "Butter", amount: "30", unit: "g", category: "Milchprodukte" },
      { name: "Knoblauch", amount: "2", unit: "Zehen", category: "Gemüse" },
      { name: "Olivenöl", amount: "2", unit: "EL", category: "Öle" },
    ],
    instructions: [],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    calories: 320,
    categories: ["Hauptgericht", "Leicht", "Gesund"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "16",
    name: "Ofenkartoffeln Brokkoli (Ofenkartoffeln Brokkoli) Dip Hähnchenbrustfilet",
    description: "Hähnchenbrust mit Ofenkartoffeln, Brokkoli und Dip",
    image: "",
    ingredients: [
      {
        name: "Hähnchenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Kartoffeln", amount: "800", unit: "g", category: "Gemüse" },
      { name: "Brokkoli", amount: "400", unit: "g", category: "Gemüse" },
      {
        name: "Sauerrahm",
        amount: "200",
        unit: "g",
        category: "Milchprodukte",
      },
      { name: "Kräuter", amount: "1", unit: "Bund", category: "Kräuter" },
      { name: "Olivenöl", amount: "3", unit: "EL", category: "Öle" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Gesund", "Gebacken"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "17",
    name: "Ofenkartoffeln Brokkoli Dip Putenbrustfilet",
    description: "Putenbrust mit Ofenkartoffeln, Brokkoli und Dip",
    image: "",
    ingredients: [
      {
        name: "Putenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Kartoffeln", amount: "800", unit: "g", category: "Gemüse" },
      { name: "Brokkoli", amount: "400", unit: "g", category: "Gemüse" },
      {
        name: "Sauerrahm",
        amount: "200",
        unit: "g",
        category: "Milchprodukte",
      },
      { name: "Kräuter", amount: "1", unit: "Bund", category: "Kräuter" },
      { name: "Olivenöl", amount: "3", unit: "EL", category: "Öle" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    calories: 450,
    categories: ["Hauptgericht", "Gesund", "Gebacken"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "18",
    name: "Heringapfelquark KaSa (Kartoffeln + Salat)",
    description: "Hering mit Apfel-Quark, Kartoffeln und Salat",
    image: "",
    ingredients: [
      { name: "Heringsfilet", amount: "400", unit: "g", category: "Fisch" },
      { name: "Quark", amount: "250", unit: "g", category: "Milchprodukte" },
      { name: "Äpfel", amount: "2", unit: "Stück", category: "Früchte" },
      { name: "Kartoffeln", amount: "600", unit: "g", category: "Gemüse" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    calories: 420,
    categories: ["Hauptgericht", "Fisch", "Traditionell"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "19",
    name: "Heringsapfelquark KäkaSa",
    description: "Hering mit Apfel-Quark, Kartoffeln und Salat",
    image: "",
    ingredients: [
      { name: "Heringsfilet", amount: "400", unit: "g", category: "Fisch" },
      { name: "Quark", amount: "250", unit: "g", category: "Milchprodukte" },
      { name: "Äpfel", amount: "2", unit: "Stück", category: "Früchte" },
      { name: "Kartoffeln", amount: "600", unit: "g", category: "Gemüse" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    calories: 420,
    categories: ["Hauptgericht", "Fisch", "Traditionell"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "20",
    name: "Hähnchenbrustfilet KäkaSa",
    description: "Hähnchenbrust mit Kartoffeln und Salat",
    image: "",
    ingredients: [
      {
        name: "Hähnchenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Kartoffeln", amount: "600", unit: "g", category: "Gemüse" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
      { name: "Olivenöl", amount: "2", unit: "EL", category: "Öle" },
      { name: "Gewürze", amount: "1", unit: "TL", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 420,
    categories: ["Hauptgericht", "Einfach", "Gesund"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "21",
    name: "Putenbrustfilet KäkaSa",
    description: "Putenbrust mit Kartoffeln und Salat",
    image: "",
    ingredients: [
      {
        name: "Putenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Kartoffeln", amount: "600", unit: "g", category: "Gemüse" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
      { name: "Olivenöl", amount: "2", unit: "EL", category: "Öle" },
      { name: "Gewürze", amount: "1", unit: "TL", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 400,
    categories: ["Hauptgericht", "Einfach", "Gesund"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "22",
    name: "Hähnchenbrustfilet/Putenbrustfilet Kartoffelsalat",
    description: "Hähnchen oder Pute mit Kartoffelsalat",
    image: "",
    ingredients: [
      {
        name: "Hähnchenbrustfilet oder Putenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Kartoffeln", amount: "800", unit: "g", category: "Gemüse" },
      { name: "Mayonnaise", amount: "150", unit: "g", category: "Saucen" },
      { name: "Gewürzgurken", amount: "100", unit: "g", category: "Gemüse" },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Senf", amount: "2", unit: "TL", category: "Saucen" },
    ],
    instructions: [],
    prepTime: 25,
    cookTime: 30,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Deutsch", "Traditionell"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "23",
    name: "Kassler Sauerkraut Nudeln/Kartoffelbrei/Schupfnudeln",
    description: "Kassler mit Sauerkraut und Beilage nach Wahl",
    image: "",
    ingredients: [
      { name: "Kassler", amount: "600", unit: "g", category: "Fleisch" },
      { name: "Sauerkraut", amount: "500", unit: "g", category: "Gemüse" },
      {
        name: "Kartoffeln oder Nudeln",
        amount: "500",
        unit: "g",
        category: "Beilage",
      },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Butter", amount: "30", unit: "g", category: "Milchprodukte" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Deutsch", "Traditionell"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "24",
    name: "Stir Fry (Mongolian)",
    description: "Mongolisches Pfannengericht mit Gemüse und Fleisch",
    image: "",
    ingredients: [
      { name: "Rindfleisch", amount: "500", unit: "g", category: "Fleisch" },
      { name: "Paprika", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Zwiebeln", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Sojasauce", amount: "100", unit: "ml", category: "Saucen" },
      { name: "Ingwer", amount: "20", unit: "g", category: "Gewürze" },
      { name: "Knoblauch", amount: "3", unit: "Zehen", category: "Gemüse" },
      { name: "Reis", amount: "300", unit: "g", category: "Getreide" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Asiatisch", "Scharf"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Würzig",
  },
  {
    id: "25",
    name: "Lachsbites Kürbis Salat",
    description: "Lachs-Häppchen mit Kürbis und Salat",
    image: "",
    ingredients: [
      { name: "Lachsfilet", amount: "500", unit: "g", category: "Fisch" },
      { name: "Kürbis", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
      { name: "Olivenöl", amount: "3", unit: "EL", category: "Öle" },
      { name: "Gewürze", amount: "1", unit: "TL", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 420,
    categories: ["Hauptgericht", "Fisch", "Gesund"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "26",
    name: "Lachsbites Kartoffeln Salat",
    description: "Lachs-Häppchen mit Kartoffeln und Salat",
    image: "",
    ingredients: [
      { name: "Lachsfilet", amount: "500", unit: "g", category: "Fisch" },
      { name: "Kartoffeln", amount: "600", unit: "g", category: "Gemüse" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
      { name: "Olivenöl", amount: "3", unit: "EL", category: "Öle" },
      { name: "Dill", amount: "1", unit: "Bund", category: "Kräuter" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 450,
    categories: ["Hauptgericht", "Fisch", "Gesund"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "27",
    name: "Lachsbites Käka Salat",
    description: "Lachs-Häppchen mit Kartoffeln und Salat",
    image: "",
    ingredients: [
      { name: "Lachsfilet", amount: "500", unit: "g", category: "Fisch" },
      { name: "Kartoffeln", amount: "600", unit: "g", category: "Gemüse" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
      { name: "Olivenöl", amount: "3", unit: "EL", category: "Öle" },
      { name: "Zitrone", amount: "1", unit: "Stück", category: "Früchte" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 450,
    categories: ["Hauptgericht", "Fisch", "Gesund"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "28",
    name: "Scholle Salat",
    description: "Gebratene Scholle mit frischem Salat",
    image: "",
    ingredients: [
      { name: "Scholle", amount: "600", unit: "g", category: "Fisch" },
      { name: "Salat gemischt", amount: "300", unit: "g", category: "Gemüse" },
      { name: "Butter", amount: "50", unit: "g", category: "Milchprodukte" },
      { name: "Zitrone", amount: "1", unit: "Stück", category: "Früchte" },
      { name: "Petersilie", amount: "1", unit: "Bund", category: "Kräuter" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    calories: 380,
    categories: ["Hauptgericht", "Fisch", "Leicht"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "29",
    name: "Scholle Pommes/Käka/Ofka/Kroketten Brokkoli/Salat",
    description: "Scholle mit Beilage nach Wahl und Gemüse",
    image: "",
    ingredients: [
      { name: "Scholle", amount: "600", unit: "g", category: "Fisch" },
      {
        name: "Pommes oder Kartoffeln",
        amount: "500",
        unit: "g",
        category: "Beilage",
      },
      {
        name: "Brokkoli oder Salat",
        amount: "300",
        unit: "g",
        category: "Gemüse",
      },
      { name: "Butter", amount: "50", unit: "g", category: "Milchprodukte" },
      { name: "Zitrone", amount: "1", unit: "Stück", category: "Früchte" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Fisch", "Klassisch"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "30",
    name: "Fischstäbchen Salat",
    description: "Knusprige Fischstäbchen mit frischem Salat",
    image: "",
    ingredients: [
      { name: "Fischstäbchen", amount: "500", unit: "g", category: "Fisch" },
      { name: "Salat gemischt", amount: "300", unit: "g", category: "Gemüse" },
      { name: "Remoulade", amount: "100", unit: "g", category: "Saucen" },
      { name: "Zitrone", amount: "1", unit: "Stück", category: "Früchte" },
    ],
    instructions: [],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 420,
    categories: ["Hauptgericht", "Fisch", "Schnell"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "31",
    name: "Hähnchenbrustfilet (Hähnchenbrustfilet) /Putenbrustfilet (Putenbrustfilet) Erdnussnudeln/Avocadonudeln Brokkoli",
    description:
      "Hähnchen oder Pute mit Erdnuss- oder Avocadonudeln und Brokkoli",
    image: "",
    ingredients: [
      {
        name: "Hähnchenbrustfilet oder Putenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Nudeln", amount: "400", unit: "g", category: "Teigwaren" },
      {
        name: "Erdnussbutter oder Avocado",
        amount: "150",
        unit: "g",
        category: "Saucen",
      },
      { name: "Brokkoli", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Sojasauce", amount: "50", unit: "ml", category: "Saucen" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Asiatisch", "Gesund"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Würzig",
  },
  {
    id: "32",
    name: "Sandwiches",
    description: "Belegte Sandwiches nach Wunsch",
    image: "",
    ingredients: [
      {
        name: "Toast oder Brot",
        amount: "8",
        unit: "Scheiben",
        category: "Brot",
      },
      { name: "Käse", amount: "150", unit: "g", category: "Milchprodukte" },
      { name: "Aufschnitt", amount: "150", unit: "g", category: "Fleisch" },
      { name: "Salat", amount: "100", unit: "g", category: "Gemüse" },
      { name: "Tomaten", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Butter", amount: "30", unit: "g", category: "Milchprodukte" },
    ],
    instructions: [],
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    calories: 380,
    categories: ["Snack", "Schnell", "Kalt"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "33",
    name: "Ratatouille Reis Ofka Lachs",
    description:
      "Französisches Gemüsegericht mit Reis, Ofenkartoffeln und Lachs",
    image: "",
    ingredients: [
      { name: "Lachsfilet", amount: "500", unit: "g", category: "Fisch" },
      { name: "Aubergine", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Zucchini", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Paprika", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Tomaten", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Reis", amount: "300", unit: "g", category: "Getreide" },
      { name: "Kartoffeln", amount: "400", unit: "g", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 45,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Französisch", "Gesund"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "34",
    name: "Hirsesalat",
    description: "Gesunder Salat mit Hirse und frischem Gemüse",
    image: "",
    ingredients: [
      { name: "Hirse", amount: "300", unit: "g", category: "Getreide" },
      { name: "Gurke", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Tomaten", amount: "3", unit: "Stück", category: "Gemüse" },
      { name: "Feta", amount: "150", unit: "g", category: "Milchprodukte" },
      { name: "Petersilie", amount: "1", unit: "Bund", category: "Kräuter" },
      { name: "Olivenöl", amount: "4", unit: "EL", category: "Öle" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    calories: 350,
    categories: ["Salat", "Vegetarisch", "Gesund"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Frisch",
  },
  {
    id: "35",
    name: "Griechischer Salat Brot",
    description: "Klassischer griechischer Salat mit Brot",
    image: "",
    ingredients: [
      { name: "Gurke", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Tomaten", amount: "4", unit: "Stück", category: "Gemüse" },
      { name: "Feta", amount: "200", unit: "g", category: "Milchprodukte" },
      { name: "Oliven", amount: "100", unit: "g", category: "Gemüse" },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Olivenöl", amount: "4", unit: "EL", category: "Öle" },
      { name: "Brot", amount: "4", unit: "Scheiben", category: "Brot" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    calories: 380,
    categories: ["Salat", "Vegetarisch", "Griechisch"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Frisch",
  },
  {
    id: "36",
    name: "Früchtequark",
    description: "Frischer Quark mit saisonalen Früchten",
    image: "",
    ingredients: [
      { name: "Quark", amount: "500", unit: "g", category: "Milchprodukte" },
      {
        name: "Beeren gemischt",
        amount: "300",
        unit: "g",
        category: "Früchte",
      },
      { name: "Honig", amount: "3", unit: "EL", category: "Süßungsmittel" },
      { name: "Nüsse", amount: "50", unit: "g", category: "Nüsse" },
    ],
    instructions: [],
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    calories: 280,
    categories: ["Dessert", "Frühstück", "Gesund"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Süß",
  },
  {
    id: "37",
    name: "Feldsalat Lachs",
    description: "Feldsalat mit gebratenem Lachs",
    image: "",
    ingredients: [
      { name: "Feldsalat", amount: "300", unit: "g", category: "Gemüse" },
      { name: "Lachsfilet", amount: "500", unit: "g", category: "Fisch" },
      { name: "Walnüsse", amount: "50", unit: "g", category: "Nüsse" },
      { name: "Balsamico", amount: "3", unit: "EL", category: "Öle" },
      { name: "Olivenöl", amount: "4", unit: "EL", category: "Öle" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    calories: 420,
    categories: ["Salat", "Fisch", "Leicht"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Frisch",
  },
  {
    id: "38",
    name: "Hackbällchen Toscana",
    description: "Italienische Hackbällchen in Tomatensauce",
    image: "",
    ingredients: [
      { name: "Hackfleisch", amount: "600", unit: "g", category: "Fleisch" },
      {
        name: "Tomaten passiert",
        amount: "500",
        unit: "g",
        category: "Gemüse",
      },
      {
        name: "Mozzarella",
        amount: "200",
        unit: "g",
        category: "Milchprodukte",
      },
      { name: "Basilikum", amount: "1", unit: "Bund", category: "Kräuter" },
      { name: "Knoblauch", amount: "3", unit: "Zehen", category: "Gemüse" },
      { name: "Parmesan", amount: "50", unit: "g", category: "Milchprodukte" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Italienisch", "Herzhaft"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "39",
    name: "Hackpaprika",
    description: "Gefüllte Paprika mit Hackfleisch",
    image: "",
    ingredients: [
      { name: "Paprika", amount: "4", unit: "Stück", category: "Gemüse" },
      { name: "Hackfleisch", amount: "500", unit: "g", category: "Fleisch" },
      { name: "Reis", amount: "200", unit: "g", category: "Getreide" },
      {
        name: "Tomaten passiert",
        amount: "400",
        unit: "g",
        category: "Gemüse",
      },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Käse", amount: "100", unit: "g", category: "Milchprodukte" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 45,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Traditionell", "Gebacken"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "40",
    name: "Hackzucchini",
    description: "Gefüllte Zucchini mit Hackfleisch",
    image: "",
    ingredients: [
      { name: "Zucchini", amount: "4", unit: "Stück", category: "Gemüse" },
      { name: "Hackfleisch", amount: "500", unit: "g", category: "Fleisch" },
      { name: "Tomaten", amount: "300", unit: "g", category: "Gemüse" },
      { name: "Käse", amount: "150", unit: "g", category: "Milchprodukte" },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Knoblauch", amount: "2", unit: "Zehen", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    calories: 420,
    categories: ["Hauptgericht", "Low Carb", "Gebacken"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "41",
    name: "Hot Dogs",
    description: "Klassische Hot Dogs mit Würstchen",
    image: "",
    ingredients: [
      { name: "Würstchen", amount: "8", unit: "Stück", category: "Fleisch" },
      {
        name: "Hot Dog Brötchen",
        amount: "8",
        unit: "Stück",
        category: "Brot",
      },
      { name: "Ketchup", amount: "100", unit: "ml", category: "Saucen" },
      { name: "Senf", amount: "50", unit: "ml", category: "Saucen" },
      { name: "Zwiebeln", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Gurken", amount: "100", unit: "g", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    calories: 480,
    categories: ["Snack", "Fast Food", "Amerikanisch"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "42",
    name: "Kürbissuppe Wirscht",
    description: "Cremige Kürbissuppe mit Würstchen",
    image: "",
    ingredients: [
      { name: "Kürbis", amount: "800", unit: "g", category: "Gemüse" },
      { name: "Würstchen", amount: "4", unit: "Stück", category: "Fleisch" },
      { name: "Sahne", amount: "200", unit: "ml", category: "Milchprodukte" },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
      { name: "Gemüsebrühe", amount: "800", unit: "ml", category: "Brühe" },
      { name: "Ingwer", amount: "20", unit: "g", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 380,
    categories: ["Suppe", "Herbst", "Cremig"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Cremig",
  },
  {
    id: "43",
    name: "Gemüsesuppe Wirscht",
    description: "Klassische Gemüsesuppe mit Würstchen",
    image: "",
    ingredients: [
      { name: "Gemüse gemischt", amount: "600", unit: "g", category: "Gemüse" },
      { name: "Würstchen", amount: "4", unit: "Stück", category: "Fleisch" },
      { name: "Kartoffeln", amount: "300", unit: "g", category: "Gemüse" },
      { name: "Gemüsebrühe", amount: "1000", unit: "ml", category: "Brühe" },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    calories: 320,
    categories: ["Suppe", "Traditionell", "Gesund"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "44",
    name: "Tomatensuppe Mozarellabrot",
    description: "Cremige Tomatensuppe mit Mozzarella-Brot",
    image: "",
    ingredients: [
      { name: "Tomaten", amount: "1000", unit: "g", category: "Gemüse" },
      { name: "Sahne", amount: "200", unit: "ml", category: "Milchprodukte" },
      { name: "Brot", amount: "4", unit: "Scheiben", category: "Brot" },
      {
        name: "Mozzarella",
        amount: "200",
        unit: "g",
        category: "Milchprodukte",
      },
      { name: "Basilikum", amount: "1", unit: "Bund", category: "Kräuter" },
      { name: "Knoblauch", amount: "2", unit: "Zehen", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 420,
    categories: ["Suppe", "Italienisch", "Cremig"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Cremig",
  },
  {
    id: "45",
    name: "Gyros (schwein / pute) pommes / brot",
    description: "Griechisches Gyros mit Pommes oder Brot",
    image: "",
    ingredients: [
      {
        name: "Schweinefleisch oder Putenfleisch",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      {
        name: "Pommes oder Brot",
        amount: "400",
        unit: "g",
        category: "Beilage",
      },
      { name: "Tzatziki", amount: "200", unit: "g", category: "Saucen" },
      { name: "Tomaten", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Zwiebeln", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Gyrosgewürz", amount: "2", unit: "EL", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    calories: 580,
    categories: ["Hauptgericht", "Griechisch", "Würzig"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Würzig",
  },
  {
    id: "46",
    name: "Fettpfänner Salat",
    description: "Deftige Pfanne mit Fleisch und Salat",
    image: "",
    ingredients: [
      {
        name: "Fleisch gemischt",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Kartoffeln", amount: "500", unit: "g", category: "Gemüse" },
      { name: "Zwiebeln", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Paprika", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Deftig", "Traditionell"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "47",
    name: "Fettpfänner Spargel",
    description: "Deftige Pfanne mit Fleisch und Spargel",
    image: "",
    ingredients: [
      {
        name: "Fleisch gemischt",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Kartoffeln", amount: "500", unit: "g", category: "Gemüse" },
      { name: "Spargel", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Zwiebeln", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Butter", amount: "50", unit: "g", category: "Milchprodukte" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 540,
    categories: ["Hauptgericht", "Deftig", "Frühling"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Herzhaft",
  },
  {
    id: "48",
    name: "Wraps Hack",
    description: "Wraps gefüllt mit Hackfleisch",
    image: "",
    ingredients: [
      { name: "Tortilla Wraps", amount: "8", unit: "Stück", category: "Brot" },
      { name: "Hackfleisch", amount: "500", unit: "g", category: "Fleisch" },
      { name: "Salat", amount: "150", unit: "g", category: "Gemüse" },
      { name: "Tomaten", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Käse", amount: "150", unit: "g", category: "Milchprodukte" },
      {
        name: "Sauerrahm",
        amount: "100",
        unit: "g",
        category: "Milchprodukte",
      },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Mexikanisch", "Schnell"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "49",
    name: "Tomatenreis Dip Fleisch/Fisch",
    description: "Tomatenreis mit Dip und Fleisch oder Fisch",
    image: "",
    ingredients: [
      { name: "Reis", amount: "300", unit: "g", category: "Getreide" },
      {
        name: "Tomaten passiert",
        amount: "400",
        unit: "g",
        category: "Gemüse",
      },
      {
        name: "Fleisch oder Fisch",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Joghurt", amount: "200", unit: "g", category: "Milchprodukte" },
      { name: "Knoblauch", amount: "2", unit: "Zehen", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Orientalisch", "Herzhaft"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Würzig",
  },
  {
    id: "50",
    name: "Lachs Avocadodip Reis",
    description: "Lachs mit Avocadodip und Reis",
    image: "",
    ingredients: [
      { name: "Lachsfilet", amount: "600", unit: "g", category: "Fisch" },
      { name: "Reis", amount: "300", unit: "g", category: "Getreide" },
      { name: "Avocado", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Limette", amount: "1", unit: "Stück", category: "Früchte" },
      { name: "Joghurt", amount: "100", unit: "g", category: "Milchprodukte" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Fisch", "Gesund"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Frisch",
  },
  {
    id: "51",
    name: "Fischcurry Reis Grünkohl",
    description: "Cremiges Fischcurry mit Reis und Grünkohl",
    image: "",
    ingredients: [
      { name: "Fischfilet", amount: "600", unit: "g", category: "Fisch" },
      { name: "Reis", amount: "300", unit: "g", category: "Getreide" },
      { name: "Grünkohl", amount: "300", unit: "g", category: "Gemüse" },
      { name: "Kokosmilch", amount: "400", unit: "ml", category: "Saucen" },
      { name: "Currypaste", amount: "3", unit: "EL", category: "Gewürze" },
      { name: "Ingwer", amount: "20", unit: "g", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Asiatisch", "Curry"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Würzig",
  },
  {
    id: "52",
    name: "Fisch Spinat Sahnesauce (Kartoffeln)",
    description: "Fisch mit Spinat in Sahnesauce und Kartoffeln",
    image: "",
    ingredients: [
      { name: "Fischfilet", amount: "600", unit: "g", category: "Fisch" },
      { name: "Spinat", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Sahne", amount: "200", unit: "ml", category: "Milchprodukte" },
      { name: "Kartoffeln", amount: "600", unit: "g", category: "Gemüse" },
      { name: "Knoblauch", amount: "2", unit: "Zehen", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Fisch", "Cremig"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Cremig",
  },
  {
    id: "53",
    name: "Lachs Kroketten/Nudeln Sahnesauce",
    description:
      "Gebratener Lachs mit Kroketten oder Nudeln und cremiger Sahnesauce",
    image: "",
    ingredients: [
      { name: "Lachsfilet", amount: "600", unit: "g", category: "Fisch" },
      {
        name: "Kroketten oder Nudeln",
        amount: "500",
        unit: "g",
        category: "Beilage",
      },
      { name: "Sahne", amount: "200", unit: "ml", category: "Milchprodukte" },
      { name: "Weißwein", amount: "100", unit: "ml", category: "Getränke" },
      { name: "Schalotte", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Butter", amount: "30", unit: "g", category: "Milchprodukte" },
      { name: "Dill", amount: "1", unit: "Bund", category: "Kräuter" },
      { name: "Zitrone", amount: "1", unit: "Stück", category: "Früchte" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 580,
    categories: ["Hauptgericht", "Fisch", "Cremig"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Cremig",
  },
  {
    id: "54",
    name: "Rindersteak Kartoffeln/Kroketten/Pommes Gemüse",
    description: "Rindersteak mit Beilage und Gemüse",
    image: "",
    ingredients: [
      { name: "Rindersteak", amount: "600", unit: "g", category: "Fleisch" },
      {
        name: "Kartoffeln oder Pommes",
        amount: "500",
        unit: "g",
        category: "Beilage",
      },
      { name: "Gemüse gemischt", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Butter", amount: "50", unit: "g", category: "Milchprodukte" },
      {
        name: "Kräuterbutter",
        amount: "80",
        unit: "g",
        category: "Milchprodukte",
      },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 620,
    categories: ["Hauptgericht", "Fleisch", "Klassisch"],
    difficulty: "Mittel",
    price: "Teuer",
    taste: "Herzhaft",
  },
  {
    id: "55",
    name: "Thunfischsteak Reis Dip/Sauce",
    description: "Gegrilltes Thunfischsteak mit Reis und Sauce",
    image: "",
    ingredients: [
      { name: "Thunfischsteak", amount: "600", unit: "g", category: "Fisch" },
      { name: "Reis", amount: "300", unit: "g", category: "Getreide" },
      { name: "Sojasauce", amount: "50", unit: "ml", category: "Saucen" },
      { name: "Ingwer", amount: "20", unit: "g", category: "Gewürze" },
      { name: "Sesam", amount: "2", unit: "EL", category: "Gewürze" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    calories: 450,
    categories: ["Hauptgericht", "Fisch", "Asiatisch"],
    difficulty: "Mittel",
    price: "Teuer",
    taste: "Würzig",
  },
  {
    id: "56",
    name: "Mangosalat Lachs/Garnelen",
    description: "Exotischer Mangosalat mit Lachs oder Garnelen",
    image: "",
    ingredients: [
      {
        name: "Lachs oder Garnelen",
        amount: "500",
        unit: "g",
        category: "Fisch",
      },
      { name: "Mango", amount: "2", unit: "Stück", category: "Früchte" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
      { name: "Limette", amount: "2", unit: "Stück", category: "Früchte" },
      { name: "Koriander", amount: "1", unit: "Bund", category: "Kräuter" },
      { name: "Chili", amount: "1", unit: "Stück", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    calories: 380,
    categories: ["Salat", "Fisch", "Exotisch"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Frisch",
  },
  {
    id: "57",
    name: "Nudeln Pesto Hähnchenbrustfilet/Pbf",
    description: "Nudeln mit Pesto und Hähnchen oder Putenbrust",
    image: "",
    ingredients: [
      { name: "Nudeln", amount: "400", unit: "g", category: "Teigwaren" },
      {
        name: "Hähnchenbrustfilet oder Putenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Pesto", amount: "150", unit: "g", category: "Saucen" },
      { name: "Parmesan", amount: "50", unit: "g", category: "Milchprodukte" },
      { name: "Pinienkerne", amount: "30", unit: "g", category: "Nüsse" },
    ],
    instructions: [],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 520,
    categories: ["Hauptgericht", "Italienisch", "Schnell"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Würzig",
  },
  {
    id: "58",
    name: "Schmandnudeln Hähnchenbrustfilet/Pbf Gemüse",
    description: "Cremige Schmandnudeln mit Hähnchen und Gemüse",
    image: "",
    ingredients: [
      { name: "Nudeln", amount: "400", unit: "g", category: "Teigwaren" },
      {
        name: "Hähnchenbrustfilet oder Putenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Schmand", amount: "200", unit: "g", category: "Milchprodukte" },
      { name: "Gemüse gemischt", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Knoblauch", amount: "2", unit: "Zehen", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 540,
    categories: ["Hauptgericht", "Cremig", "Pasta"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Cremig",
  },
  {
    id: "59",
    name: "Tomatel Mozarella Brot/Kartoffelnquark",
    description: "Tomate-Mozzarella mit Brot oder Kartoffelquark",
    image: "",
    ingredients: [
      { name: "Tomaten", amount: "4", unit: "Stück", category: "Gemüse" },
      {
        name: "Mozzarella",
        amount: "250",
        unit: "g",
        category: "Milchprodukte",
      },
      { name: "Basilikum", amount: "1", unit: "Bund", category: "Kräuter" },
      {
        name: "Brot oder Kartoffeln",
        amount: "400",
        unit: "g",
        category: "Beilage",
      },
      { name: "Quark", amount: "200", unit: "g", category: "Milchprodukte" },
      { name: "Olivenöl", amount: "4", unit: "EL", category: "Öle" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    calories: 420,
    categories: ["Hauptgericht", "Italienisch", "Vegetarisch"],
    difficulty: "Einfach",
    price: "Günstig",
    taste: "Frisch",
  },
  {
    id: "60",
    name: "Körniger Frischkäse Nudeln Hackfleisch",
    description: "Nudeln mit körnigem Frischkäse und Hackfleisch",
    image: "",
    ingredients: [
      { name: "Nudeln", amount: "400", unit: "g", category: "Teigwaren" },
      { name: "Hackfleisch", amount: "500", unit: "g", category: "Fleisch" },
      {
        name: "Körniger Frischkäse",
        amount: "300",
        unit: "g",
        category: "Milchprodukte",
      },
      { name: "Tomaten", amount: "300", unit: "g", category: "Gemüse" },
      { name: "Zwiebeln", amount: "1", unit: "Stück", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 580,
    categories: ["Hauptgericht", "Pasta", "Proteinreich"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Cremig",
  },
  {
    id: "61",
    name: "Sojasaucenlachs Spinat Reis",
    description: "Lachs in Sojasauce mit Spinat und Reis",
    image: "",
    ingredients: [
      { name: "Lachsfilet", amount: "600", unit: "g", category: "Fisch" },
      { name: "Spinat", amount: "400", unit: "g", category: "Gemüse" },
      { name: "Reis", amount: "300", unit: "g", category: "Getreide" },
      { name: "Sojasauce", amount: "80", unit: "ml", category: "Saucen" },
      { name: "Ingwer", amount: "20", unit: "g", category: "Gewürze" },
      { name: "Knoblauch", amount: "2", unit: "Zehen", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Asiatisch", "Fisch"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Würzig",
  },
  {
    id: "62",
    name: "Fisch Tacos",
    description: "Mexikanische Tacos mit Fisch",
    image: "",
    ingredients: [
      { name: "Fischfilet", amount: "600", unit: "g", category: "Fisch" },
      { name: "Tortillas", amount: "8", unit: "Stück", category: "Brot" },
      { name: "Kohl", amount: "200", unit: "g", category: "Gemüse" },
      { name: "Avocado", amount: "2", unit: "Stück", category: "Gemüse" },
      { name: "Limette", amount: "2", unit: "Stück", category: "Früchte" },
      {
        name: "Sauerrahm",
        amount: "100",
        unit: "g",
        category: "Milchprodukte",
      },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    calories: 480,
    categories: ["Hauptgericht", "Mexikanisch", "Fisch"],
    difficulty: "Mittel",
    price: "Mittel",
    taste: "Frisch",
  },
  {
    id: "63",
    name: "Zucchiniküchle Salat Dip",
    description: "Gebratene Zucchini-Puffer mit Salat und Dip",
    image: "",
    ingredients: [
      { name: "Zucchini", amount: "600", unit: "g", category: "Gemüse" },
      { name: "Eier", amount: "2", unit: "Stück", category: "Eier" },
      { name: "Mehl", amount: "100", unit: "g", category: "Getreide" },
      { name: "Salat gemischt", amount: "200", unit: "g", category: "Gemüse" },
      {
        name: "Kräuterquark",
        amount: "200",
        unit: "g",
        category: "Milchprodukte",
      },
    ],
    instructions: [],
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    calories: 320,
    categories: ["Hauptgericht", "Vegetarisch", "Leicht"],
    difficulty: "Mittel",
    price: "Günstig",
    taste: "Herzhaft",
  },
  {
    id: "64",
    name: "Pestohähnchen",
    description: "Hähnchen in Pestomarinade gebraten",
    image: "",
    ingredients: [
      {
        name: "Hähnchenbrustfilet",
        amount: "600",
        unit: "g",
        category: "Fleisch",
      },
      { name: "Pesto", amount: "150", unit: "g", category: "Saucen" },
      { name: "Parmesan", amount: "50", unit: "g", category: "Milchprodukte" },
      { name: "Olivenöl", amount: "2", unit: "EL", category: "Öle" },
      { name: "Knoblauch", amount: "2", unit: "Zehen", category: "Gemüse" },
    ],
    instructions: [],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 420,
    categories: ["Hauptgericht", "Italienisch", "Schnell"],
    difficulty: "Einfach",
    price: "Mittel",
    taste: "Würzig",
  },
];

// Provider component
export const RecipeProvider = ({ children }) => {
  // State for recipes
  const [recipes, setRecipes] = useState(() => {
    const localData = localStorage.getItem("recipes");
    // Füge die neuen Rezepte zu den vorhandenen hinzu
    return localData ? JSON.parse(localData) : sampleRecipes;
  });

  // State for meal plan
  const [mealPlan, setMealPlan] = useState(() => {
    const localData = localStorage.getItem("mealPlan");
    return localData
      ? JSON.parse(localData)
      : {
          monday: [],
          tuesday: [],
          wednesday: [],
          thursday: [],
          friday: [],
          saturday: [],
          sunday: [],
        };
  });

  // State for shopping list
  const [shoppingList, setShoppingList] = useState(() => {
    const localData = localStorage.getItem("shoppingList");
    return localData ? JSON.parse(localData) : [];
  });

  // Save to localStorage when recipes change
  useEffect(() => {
    localStorage.setItem("recipes", JSON.stringify(recipes));
  }, [recipes]);

  // Save to localStorage when meal plan changes
  useEffect(() => {
    localStorage.setItem("mealPlan", JSON.stringify(mealPlan));
  }, [mealPlan]);

  // Save to localStorage when shopping list changes
  useEffect(() => {
    localStorage.setItem("shoppingList", JSON.stringify(shoppingList));
  }, [shoppingList]);

  // Add a new recipe
  const addRecipe = (recipe) => {
    const newRecipe = {
      ...recipe,
      id: Date.now().toString(),
    };
    setRecipes([...recipes, newRecipe]);
  };

  // Delete a recipe
  const deleteRecipe = (id) => {
    setRecipes(recipes.filter((recipe) => recipe.id !== id));

    // Also remove from meal plan
    const updatedMealPlan = { ...mealPlan };
    Object.keys(updatedMealPlan).forEach((day) => {
      updatedMealPlan[day] = updatedMealPlan[day].filter(
        (recipeId) => recipeId !== id
      );
    });
    setMealPlan(updatedMealPlan);
  };

  // Update a recipe
  const updateRecipe = (id, updatedRecipe) => {
    setRecipes(
      recipes.map((recipe) =>
        recipe.id === id ? { ...recipe, ...updatedRecipe } : recipe
      )
    );
  };

  // Add recipe to meal plan
  const addToMealPlan = (day, recipeId) => {
    setMealPlan({
      ...mealPlan,
      [day]: [...mealPlan[day], recipeId],
    });
  };

  // Remove recipe from meal plan
  const removeFromMealPlan = (day, recipeId) => {
    setMealPlan({
      ...mealPlan,
      [day]: mealPlan[day].filter((id) => id !== recipeId),
    });
  };

  // Generate shopping list from meal plan
  const generateShoppingList = () => {
    const newShoppingList = [];
    const allRecipeIds = Object.values(mealPlan).flat();

    allRecipeIds.forEach((recipeId) => {
      const recipe = recipes.find((r) => r.id === recipeId);
      if (recipe) {
        recipe.ingredients.forEach((ingredient) => {
          // Check if ingredient already exists in shopping list
          const existingIndex = newShoppingList.findIndex(
            (item) =>
              item.name.toLowerCase() === ingredient.name.toLowerCase() &&
              item.unit === ingredient.unit
          );

          if (existingIndex >= 0) {
            // If it exists, add the amount
            const existingAmount =
              parseFloat(newShoppingList[existingIndex].amount) || 0;
            const newAmount = parseFloat(ingredient.amount) || 0;

            if (!isNaN(existingAmount) && !isNaN(newAmount)) {
              newShoppingList[existingIndex].amount = (
                existingAmount + newAmount
              ).toString();
            }
          } else {
            // Otherwise add new ingredient to shopping list
            newShoppingList.push({
              ...ingredient,
              checked: false,
            });
          }
        });
      }
    });

    // Sort by category
    newShoppingList.sort((a, b) => a.category.localeCompare(b.category));

    setShoppingList(newShoppingList);
  };

  // Toggle item checked in shopping list
  const toggleShoppingItem = (index) => {
    const updatedList = [...shoppingList];
    updatedList[index].checked = !updatedList[index].checked;
    setShoppingList(updatedList);
  };

  // Clear shopping list
  const clearShoppingList = () => {
    setShoppingList([]);
  };

  return (
    <RecipeContext.Provider
      value={{
        recipes,
        mealPlan,
        shoppingList,
        addRecipe,
        deleteRecipe,
        updateRecipe,
        addToMealPlan,
        removeFromMealPlan,
        generateShoppingList,
        toggleShoppingItem,
        clearShoppingList,
      }}
    >
      {children}
    </RecipeContext.Provider>
  );
};
